language: python
install: echo "Install test dependencies"
script: echo "Run tests"
python: "2.7"
before_deploy:
  - pip install git+https://github.com/romanvm/kodi-addon-submitter.git
  - submit-addon -z screensaver.kaster # Create an installable ZIP
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  # Publish an installable ZIP to GitHub Releases
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  # Submit to the official Kodi repository
  - provider: script
    script: submit-addon -r repo-plugin -b krypton --pull-request screensaver.kaster
    on:
      tags: true
notifications:
  email: false
